# Generated by Django 3.0a1 on 2019-10-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=25)),
                ('FirsrName', models.CharField(max_length=25)),
                ('Sheild', models.IntegerField(max_length=4)),
                ('Tour', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('Platoon', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('TED', models.DateField()),
                ('ODA', models.DateField()),
            ],
        ),
    ]
