# Generated by Django 3.0a1 on 2019-10-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lts',
            name='Sheild',
        ),
    ]
