# Generated by Django 3.0a1 on 2019-10-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_lts_sheild'),
    ]

    operations = [
        migrations.AddField(
            model_name='lts',
            name='Shield',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
