# Generated by Django 3.0a1 on 2019-10-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_lts_shield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LTS',
            new_name='LT',
        ),
    ]
