# Generated by Django 3.0a1 on 2019-10-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20191020_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=25)),
                ('First_Name', models.CharField(max_length=25)),
                ('Shield', models.IntegerField()),
                ('Tour', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('Platoon', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('Unit', models.CharField(max_length=4)),
                ('ODA', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MEDIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=25)),
                ('First_Name', models.CharField(max_length=25)),
                ('Shield', models.IntegerField()),
                ('Tour', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('Platoon', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('Unit', models.CharField(max_length=4)),
                ('TED', models.DateField()),
                ('ODA', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='lt',
            old_name='FirsrName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='lt',
            old_name='LastName',
            new_name='Last_Name',
        ),
    ]
